compatibility_date = "DATE"
name = "nosflare"
workers_dev = false
main = "dist/worker.js"
kv_namespaces = [
    { binding = "relayDb", id = "KV_ID" }
]
routes = [
    { pattern = "FULL_DOMAIN", custom_domain = true }
]
